# Generated by Django 5.2.9 on 2026-04-04 20:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pawncontract_interest_accrued_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('LAPTOP', 'Laptop'), ('PHONE', 'Celular'), ('JEWELRY', 'Joya'), ('APPLIANCE', 'Electrodoméstico'), ('CONSOLE', 'Consola'), ('INSTRUMENT', 'Instrumento musical'), ('OTHER', 'Otro')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('has_box', models.BooleanField(default=False)),
                ('has_charger', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pawncontract')),
            ],
        ),
    ]
