# Generated by Django 5.2.9 on 2026-04-09 23:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cashflow_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdenomination',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cashexpense',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='profit_rate_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Porcentaje de la utilidad (interés) que corresponde al inversionista. Ej: 50.00 = 50%', max_digits=5),
        ),
    ]
