# Generated by Django 5.2.9 on 2026-04-10 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_cashdenomination_id_alter_cashexpense_id_and_more'),
        ('core', '0024_mvi_condition'),
    ]

    operations = [
    ]
