# Generated by Django 5.2.9 on 2026-04-13 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_interest_config_customer_rate_pawnitem_loanamount'),
        ('core', '0025_merge_20260410_1823'),
    ]

    operations = [
    ]
