# Generated by Django 5.2.9 on 2026-04-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20260412_2055'),
        ('core', '0026_sync_phase'),
    ]

    operations = [
    ]
