# Generated by Django 5.2.9 on 2026-04-15 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_0026_merge_20260412_2055_0026_sync_phase'),
        ('core', '0027_remove_max_principal'),
    ]

    operations = [
    ]
