# Generated by Django 5.2.9 on 2026-04-15 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_directpurchase_purchase_date'),
        ('core', '0028_merge_20260414_2051'),
    ]

    operations = [
    ]
