# Generated by Django 5.2.9 on 2026-04-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_pawnrenewal_effective_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawnrenewal',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Fecha real de la operación para registros históricos', null=True),
        ),
    ]
